import { cssr } from 'dsh-tauri-ui/client'

const { c } = cssr

/** 工作树状态条（surface.tsx）：会话下方状态条 + 折叠日志。 */
export default c([
  c('.dshp-worktree__surface', {
    boxSizing: 'border-box',
    width: 'calc(100% - 2 * var(--dsh-composer-side-clearance) - 4 * var(--dsh-composer-dock-inset))',
    maxWidth: 'calc(var(--dsh-composer-card-max-width) - 4 * var(--dsh-composer-dock-inset))',
    margin: '0 auto',
    alignSelf: 'center',
  }),
  c('.dshp-worktree__surface-bar', {
    boxSizing: 'border-box',
    width: '100%',
    position: 'relative',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '4px 5px 4px 12px',
    margin: '0 auto',
    border: '1px solid var(--dsw-alias-border-l1)',
    borderRadius: '12px',
    background: 'var(--dsw-specific-tip)',
    color: 'var(--dsw-alias-label-primary)',
    pointerEvents: 'auto',
  }),
  c('.dshp-worktree__surface-content', { display: 'flex', alignItems: 'center', gap: '5px' }),
  c('.dshp-worktree__surface-label', { fontSize: '13px', lineHeight: '20px', fontWeight: 500 }),
  c('.dshp-worktree__action', {
    height: '26px',
    padding: '0 10px',
    border: 'none',
    borderRadius: '7px',
    fontFamily: 'inherit',
    fontSize: '12px',
    cursor: 'pointer',
    color: 'var(--dsw-alias-label-primary)',
    background: 'var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,0.08))',
    whiteSpace: 'nowrap',
  }),
  c('.dshp-worktree__action.dshp-worktree__action--log', { padding: 0, fontSize: '13px', background: 'transparent', textDecoration: 'underline' }),
  c('.dshp-worktree__action.dshp-worktree__action--danger', { color: 'var(--dsw-alias-danger-foreground, #c0392b)', background: 'transparent' }),
  c('.dshp-worktree__spacer', { flex: 1 }),
  c('.dshp-worktree__logs', {
    display: 'grid',
    gridTemplateRows: '0fr',
    opacity: 0,
    transition: 'grid-template-rows 180ms cubic-bezier(.16, 1, .3, 1), opacity 140ms ease',
  }),
  c('.dshp-worktree__logs.dshp-worktree__logs--open', { gridTemplateRows: '1fr', opacity: 1 }),
  c('.dshp-worktree__logs-inner', { minHeight: 0, overflow: 'hidden' }),
  c('.dshp-worktree__logs-panel', {
    maxHeight: '180px',
    overflowY: 'auto',
    padding: '10px',
    borderRadius: '10px',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-base)',
    zIndex: 30,
  }),
  c('.dshp-worktree__log-line', { fontSize: '12px', fontFamily: 'cursive', lineHeight: '16px' }),
])
